### ISSUE TITLE
feature request: custom diff for chart values

### ISSUE THREAD

**Issue by jhoblitt** [hashicorp/terraform-provider-helm#305] opened 2019-07-11 18:09 UTC
At present, the default "diff" for chart values is virtually useless for all but the most basic of chart configuration due to the size of yaml strings being compared.  Eg., "`(giant string) => (giant string)`" It would be preferable a custom diff format, perhaps in unified context format (`diff -u`), that would make it possible to [reasonably] identify which yaml keys/values are changing.

**Comment by servo1x** [comment] 2019-07-26 10:27
Does anyone have a solution for this with the change in output formatting for terraform 0.12? I used to use landscape to get the chart values diff, but it only works with terraform 0.11.

**Comment by okgolove** [comment] 2019-08-22 10:58
It would be definitely useful thing.

**Comment by muscovitebob** [comment] 2020-06-17 13:35
The way the helm diff plugin does it is quite neat (used by helmfile for example). It is possible to reproduce that behaviour within the constraints of terraform?

**Comment by gordonbondon** [comment] 2020-07-22 02:02
I did an initial WIP on trying to use helm-diff here #553, please give it a try.

**Comment by dak1n1** [comment] 2021-04-27 00:28
Closing since this was released in v2.1.0. https://github.com/hashicorp/terraform-provider-helm/pull/702

**Closed as completed by dak1n1** 2021-04-27 00:28 UTC
Labels: enhancement, size/M, needs-investigation, acknowledged, theme/diffs
