### ISSUE TITLE
Helm release not found by Helm provider

### ISSUE THREAD

**Issue by artazar** [hashicorp/terraform-provider-helm#585] opened 2020-09-10 06:19 UTC
### Terraform Version and Provider Version
$ terraform -v
Terraform v0.12.29

### Provider Version
+ provider.helm v1.3.0
+ provider.kubernetes v1.13.1

### Affected Resource(s)
helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "prometheus" {
  name       = "prometheus"
  repository = "stable"
  chart      = "prometheus-operator"
  version    = var.prometheus_operator_chart_version
  namespace  = "monitoring"

  values = [
    local_file.prometheus_operator_values.content
  ]

  depends_on = [local_file.prometheus_operator_values]
}
```

### Debug Output

Here is the point of error, unfortunately it doesn't go more verbose than that:

	Line 5716: 2020-09-10T08:52:55.145+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] [resourceReleaseExists: prometheus] Start
	Line 5717: 2020-09-10T08:52:55.145+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] [INFO] GetHelmConfiguration start
	Line 5718: 2020-09-10T08:52:55.145+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [INFO] Successfully initialized kubernetes config
	Line 5719: 2020-09-10T08:52:55.145+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] [INFO] GetHelmConfiguration success
	Line 5720: 2020-09-10T08:52:55.145+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] prometheus getRelease wait for lock
	Line 5721: 2020-09-10T08:52:55.145+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] prometheus getRelease got lock, started
	Line 5722: 2020-09-10T08:52:55.145+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] prometheus getRelease post action created
	Line 5794: 2020-09-10T08:52:55.556+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] prometheus getRelease post run
	Line 5795: 2020-09-10T08:52:55.556+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] getRelease for prometheus errored
	Line 5796: 2020-09-10T08:52:55.556+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] release: not found
	Line 5797: 2020-09-10T08:52:55.556+0300 [DEBUG] plugin.terraform-provider-helm_v1.3.0_x4: 2020/09/10 08:52:55 [DEBUG] [resourceReleaseExists: prometheus] Done

This is collected with TF_LOG=debug and HELM_DEBUG=1
Is it possible to get more details in logs and what could be the possible reasons for getRelease to fail?

### Expected Behavior
No errors, Helm release is visible to Helm provider.

### Actual Behavior
Error prevents Helm provider to list the existing release.

### Steps to Reproduce

1. Run `terraform apply` for the Helm release resource.
2. The release gets created successfully, no errors.
3. Run `terraform apply` again - see the release is suggested to be created again. Helm provider fails to find already existing release.

### Important Factoids
1. This is a GKE cluster v1.15.
2. Helm v3 is used.
3. Helm provider is initiated with a local kubeconfig file:

```
provider "helm" {
    version = "1.3.0"

    kubernetes {
      config_path = local_file.kubeconfig.filename
    }
}
```

4. Listing the release directly with Helm looks good:

```
$ helm3 --kubeconfig d003-sb2-k8s-euwe1.kubeconfig -n monitoring ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
prometheus      monitoring      1               2020-09-10 09:12:21.1668459 +0300 MSK   deployed        prometheus-operator-8.13.8      0.38.1
```

5. Checked Helm provider versions 1.1.1, 1.2.4, 1.3.0 - they all face the same behavior.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment] 2020-10-12 22:37
@artazar What if you try using the latest helm provider, and latest prometheus-community helm chart? That seemed to work for me. If that's not an option, please provide a Terraform config file that will reproduce the issue. Thanks,

Here are some details from my testing:

I tried to reproduce this and noticed the helm chart being installed was deprecated: https://github.com/helm/charts/tree/master/stable/prometheus-operator it now lives here: https://github.com/prometheus-community/helm-charts

Using the newer version of the prometheus chart, this seemed to work.

This was my Terraform config to reproduce the issue:

```
resource "local_file" "kubeconfig" {
    content     = file("/home/dakini/.kube/config")
    filename = "./testconfig"
}

resource "local_file" "prometheus_operator_values" {
    content     = file("./values.yaml")
    filename = "./testvalues"
}

variable "prometheus_operator_chart_version" {
  type = string
  default = "9.0"
}

provider "helm" {
    kubernetes {
      config_path = local_file.kubeconfig.filename
    }
}

resource "helm_release" "prometheus" {
  name       = "prometheus-community"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "prometheus-operator"
  version    = var.prometheus_operator_chart_version
  namespace  = "default"

  values = [
    local_file.prometheus_operator_values.content
  ]

  depends_on = [local_file.prometheus_operator_values]
}
```

The result was a successful install:

```
$ kubectl get pods
NAME                                                       READY   STATUS    RESTARTS   AGE
alertmanager-prometheus-community-prome-alertmanager-0     2/2     Running   0          2m38s
prometheus-community-grafana-7dc7fb4957-7592q              2/2     Running   0          2m43s
prometheus-community-kube-state-metrics-7d59c5c965-fg6tf   1/1     Running   0          2m43s
prometheus-community-prome-operator-74847594c5-wvqlc       2/2     Running   0          2m43s
prometheus-community-prometheus-node-exporter-gkbtq        1/1     Running   0          2m43s
prometheus-prometheus-community-prome-prometheus-0         3/3     Running   1          2m28s
```

And the second plan/apply comes up empty, which is good:

```
$ terraform apply
local_file.kubeconfig: Refreshing state... [id=c6bbe59b64cd6a5fb48f90c9104f9475bc6f0501]
local_file.prometheus_operator_values: Refreshing state... [id=0c15f411827025c2851ccf03f4dbcfdd7c0746e2]
helm_release.prometheus: Refreshing state... [id=prometheus-community]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by artazar** [comment] 2020-10-20 08:12
@dak1n1 Thanks, while it does not explain the original issue, moving to the new chart repository indeed helps to overcome the issue.

**Comment by aareet** [comment] 2020-12-11 04:14
@artazar since the issue is resolved with newer versions of the provider/chart, I'll close this. If someone has an issue they can reopen with a reproducing config.

**Closed as completed by aareet** 2020-12-11 04:14 UTC
Labels: bug
