### ISSUE TITLE
helm_release. error installing: Post https://.../deployments: x509: certificate signed by unknown authority (AWS EKS)

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-helm#162] opened 2018-11-29 15:37 UTC
### Terraform Version

Terraform v0.11.10

### Affected Resource(s)

- helm_resource
- helm_repository

### Terraform Configuration Files
```hcl
provider "helm" {
    service_account = "tiller"
    namespace = "kube-system"
    kubernetes {
        insecure = true
        host = "${data.terraform_remote_state.devops-beaver-aws-eks.aws_eks_cluster.demo.endpoint}"
        config_context = "${data.terraform_remote_state.devops-beaver-aws-eks.kubeconfig}"
    }
}
```
### Expected Behavior

skiping TLS verification

### Actual Behavior

ignores all setting in kubernetes block and polling local $HOME/.kube.config
trying to connect to localhost:8080

### Steps to Reproduce

1. `terraform apply`

**Comment by meyskens** [comment] 2019-02-25 13:41
I am unable to replicate this. Could you provide me with a full configuration example where you get this? Preferably on Minikube if possible. Thanks!

**Comment by soudaburger** [comment] 2019-02-26 16:55
I can attest to seeing similar things... I can reproduce it, wherein it keeps happening to me.  I can successfully run `terraform *` commands and everything works, then all of a sudden, i get the `error installing: Post https://...` messages.

Running terraform version: 0.11.11
Running with helm.provider version: 0.8.0
Targeting GKE k8s deployment.

**Comment by mcuadros** [comment] 2020-04-10 18:34
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.

**Closed as completed by mcuadros** 2020-04-10 18:34 UTC

**Comment by joeljohnston** [comment] 2020-04-14 17:39
I'm using the code checked out from https://github.com/terraform-aws-modules/terraform-aws-eks.git (master branch) and getting the same error at the very tail end of the terraform deployment process.
