### ISSUE TITLE
Helm provider 2.0.1 not tracking helm package change

### ISSUE THREAD

**Issue by goddini91** [hashicorp/terraform-provider-helm#664] opened 2021-01-19 10:01 UTC
Terraform version: 0.13.5
Kubernetes version: 1.18
Helm version: v3.4.2
Terraform provider helm: 2.01

### Affected Resource(s)
- helm_release

### After migration from 1.3.2 to 2.0.1 version  

If delete helm package by the run the command  "helm del name_package" and run terraform apply on version provider-helm 1.3.2 application will be installed if do the same on provider-helm 2.0.1 and 2.0.2 command "helm del name_package" terraform will not track change and will do nothing.

Could you help solve this problem or find the way how helm provider can tracking the change in helm package.

**Comment by aareet** [comment] 2021-01-19 16:24
I believe this is a duplicate of #662

**Closed as completed** 2021-01-19 17:13 UTC
Labels: bug
