### ISSUE TITLE
New resource shouldn't be required when a chart is updated

### ISSUE THREAD

**Issue by mstrzele** [hashicorp/terraform-provider-helm#32] opened 2017-11-28 15:38 UTC
```
-/+ helm_chart.fluent_bit (new resource required)
      id:         "fluent-bit" => <computed> (forces new resource)
      chart:      "http://mstrzele-charts.s3-website-eu-west-1.amazonaws.com/fluent-bit-0.1.0.tgz" => "http://mstrzele-charts.s3-website-eu-west-1.amazonaws.com/fluent-bit-0.1.1.tgz" (forces new resource)
```

As you can see, I've changed the chart version only. IMHO it shouldn't cause a recreation of the whole release.

**Comment by sagikazarmark** [comment] 2018-01-23 06:21
This looks like a duplicate of #26

**Comment by mcuadros** [comment] 2018-02-26 09:11
In theory fixed by https://github.com/mcuadros/terraform-provider-helm/pull/39, if not reopen the issue

**Closed as completed by mcuadros** 2018-02-26 09:11 UTC

**Comment by sagikazarmark** [comment] 2018-02-26 12:47
I started using this provider again for a few weeks now, so far nothing like that.

**Comment by oba11** [comment] 2018-12-26 13:46
Seem like this issue somehow resurfaced again
