### ISSUE TITLE
Helm release always show changes on same values file

### ISSUE THREAD

**Issue by weeco** [hashicorp/terraform-provider-helm#617] opened 2020-11-04 15:23 UTC
### Terraform Version and Provider Version

v0.13.5

### Provider Version
v1.3.2

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "kube_state_metrics" {
  name       = "kube-state-metrics"
  namespace  = kubernetes_namespace.monitoring.metadata.0.name
  repository = "https://kubernetes-charts.storage.googleapis.com"
  chart      = "kube-state-metrics"
  version    = "2.9.1"

  values = [
    file("${path.module}/kube_state_metrics.yaml")
  ]
}
```

### The problem

Every time I want to apply the above helm release it shows a change in the values. The plan and apply diff however show the exact same contents from that values.yaml file. If I apply this change it seems like the helm release will actually be reinstalled.

I did not expect any changes to appear in the diff because the values haven't changed. My hypothesis is that this is caused by different line endings in the values.yaml file as multiple collaborators with different OS (Mac, Linux + Windows) work on this repository. 

This is such a plan result:

![image](https://user-images.githubusercontent.com/23424570/98129962-04e81100-1eba-11eb-98c3-6068d6bef68f.png)

### Steps to Reproduce

1. `terraform apply`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment] 2020-11-18 03:39
I think this is a duplicate of https://github.com/hashicorp/terraform-provider-helm/issues/543

**Comment by jrhouston** [comment] 2020-11-18 21:00
I'm going to close this and use #543 to track.

**Closed as completed by jrhouston** 2020-11-18 21:00 UTC
Labels: bug
