### ISSUE TITLE
Any plans as of the morning of Dec 16th with helm_releases in EKS attempt to change version of helm release to 0.2.2

### ISSUE THREAD

**Issue by ajcann** [hashicorp/terraform-provider-helm#645] opened 2020-12-17 02:57 UTC
As strange as it sounds, across 8 clusters with 0 local or remote state changes and with no module changes (confirmed with three engineers), any attempt to create a plan that should result in nothing attempt to change versions of all installed helm_releases from whatever their current version is to 0.2.2.

**Comment by doug-ba** [comment] 2020-12-17 03:41
This exact problem is affecting us, too.  We're running Terraform v0.12.21, terraform-provider-helm_v1.0.0_x4 (but also tried latest).
I use a local plugin cache, so the plugin did not change.

We made no changes to our terraform code.  This worked normally yesterday.

This is the relevant section of my debug log:
`2020/12/16 17:01:52 [WARN] Provider "registry.terraform.io/-/helm" produced an invalid plan for helm_release.ordered_helm_release[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .version: planned value cty.StringVal("0.2.2") does not match config value cty.StringVal("1.33.1") nor prior value cty.StringVal("1.33.1")`
`2020/12/16 17:01:53 [WARN] Provider "registry.terraform.io/-/helm" produced an invalid plan for helm_release.openstack_external_dns[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .version: planned value cty.StringVal("0.2.2") does not match config value cty.StringVal("2.19.1") nor prior value cty.StringVal("2.19.0")`

**Comment by jharris-** [comment] 2020-12-17 03:43
I am also seeing this on a few non-managed kube clusters.
```
2020/12/16 19:11:40 [WARN] Provider "registry.terraform.io/-/helm" produced an invalid plan for helm_release.ordered_helm_release[0], but we are tolerating it because it is using t
he legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .version: planned value cty.StringVal("0.2.2") does not match config value cty.StringVal("1.33.1") nor prior value cty.StringVal("1.33.1")
```

**Comment by ajcann** [comment] 2020-12-17 03:51
Okay I think the issue might be that the default repository ( https://github.com/helm/charts ) is now deprecated and creating unspecified behavior. Updating the repository field to an actively supported repo with your charts is likely the fix here. Testing now.

**Comment by doug-ba** [comment] 2020-12-17 05:55
Looks like you may be right.  I switched my "stable" repository to point to https://charts.helm.sh/stable as outlined here: https://helm.sh/blog/new-location-stable-incubator-charts/ and am no longer seeing the incorrect version.  I haven't actually applied the changes yet.

**Comment by yasra002** [comment] 2020-12-17 12:32
I tested updating the repository field and it worked for us and problem was solved.

**Comment by AndreaGiardini** [comment] 2020-12-17 14:48
I can confirm that updating the repository field worked for us. No redeploy needed

**Comment by jrhouston** [comment] 2020-12-17 16:07
Yeah this will likely have been caused by the the stable repository being sunset. We haven't put out a new release of the provider yet. See their [documentation](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline) for more details.

**Comment by tomerliberman** [comment] 2020-12-17 16:50
catch 0.2.2  authored by helm provider
thanks @doug-ba for the link, applied new urls and back to normal

**Comment by andreabolandrina** [comment] 2020-12-18 16:16
that "0.2.2" version everywhere seemed a bit weird.
In my case, I had to replace https://kubernetes-charts.storage.googleapis.com with https://charts.helm.sh/stable/.

**Comment by aareet** [comment] 2021-01-06 17:04
Closing this issue since the solution is discussed above.

**Closed as completed by aareet** 2021-01-06 17:04 UTC
Labels: bug
