### ISSUE TITLE
Exec plugins doesn't work

### ISSUE THREAD

**Issue by fazizsoltani** [hashicorp/terraform-provider-helm#968] opened 2022-10-11 10:44 UTC
Hi, I want to use this provider with the exec plugin. But, it doesn't work for me and I got an error message.

```
Terraform version: v1.3.2
provider version: 2.7.0
Kubernetes version: 1.21
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    exec {
      api_version = "client.authentication.k8s.io/v1alpha1"
      args        = ["eks", "get-token", "--cluster-name", data.aws_eks_cluster_auth.cluster.token]
      command     = "aws"
    }
  }
}
Or
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}

```

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
I expected to work smoothly

### Actual Behavior
I got this error message
```
│ Error: Kubernetes cluster unreachable: invalid configuration: context was not found for specified context: XXXXXXXX
│
│   with module.alb.helm_release.aws-load-balancer-controller,
│   on modules/alb/main.tf line 98, in resource "helm_release" "aws-load-balancer-controller":
│   98: resource "helm_release" "aws-load-balancer-controller" {
```

**Comment by stevehipwell** [comment] 2022-10-11 17:25
We're seeing a similar and likely related issue when trying to create new `helm-release` resources with `v2.7.0` using the exec plugin. Reverting to `v2.6.0` fixes the issue.

>
│ Error: execution error at (aws-load-balancer-controller/templates/deployment.yaml:61:28): Chart cannot be installed without a valid clusterName!
│ 
│   with module.eks.module.core_config.module.aws_load_balancer_controller.helm_release.default,
│   on .terraform/modules/eks/modules/core-config/modules/aws-load-balancer-controller/main.tf line 36, in resource "helm_release" "default":
│   36: resource "helm_release" "default" {

**Comment by jrhouston** [comment] 2022-10-12 19:56
@stevehipwell could you open a separate issue with your configuration so we can try and reproduce. The issue above seems to be an issue with the provider block, whereas the error you've shared points to a problem with the chart templating.

**Comment by stevehipwell** [comment] 2022-10-13 16:17
@jrhouston the fact that this issue only affects new resources being added to an existing cluster makes me think that it has the same root cause? I'm happy to open a new issue if that works best for you but as the issue is resolved by a version rollback I assumed it'd be best to keep the issue count down if it was a single regression.

**Comment by superbspeed** [comment] 2022-10-19 01:50
Using api version `v1beta1` and `data.aws_eks_cluster.cluster.id` works for me.

**Closed as completed** 2022-12-14 09:45 UTC
