### ISSUE TITLE
TFC runner using helm_release produces 404 when chart is not a full url

### ISSUE THREAD

**Issue by fdr2** [hashicorp/terraform-provider-helm#929] opened 2022-08-10 12:50 UTC
### Description

When using the helm_release resource in Terraform Cloud, the [Chart Repository](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#example-usage---chart-repository) usage produces a `not found` error with no message clearly indicating a fix for the issue, since this chart version is available.

Error Message:
> Error: could not download chart: chart "jetstack/cert-manager" version "v0.14.3" not found in https://charts.jetstack.io repository

Ivan from Terraform Cloud Support pointed out that using the [Chart URL](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#example-usage---chart-url) method resolves this issue and I have confirmed this works as expected, but it would be helpful for posterity if this was clearly documented in the provider.

### Potential Terraform Configuration

The following format produces a `Not Found` error when run from a remote runner in TFC.
```hcl
resource "helm_release" "example" {
  name       = "my-redis-release"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "redis"
  version    = "6.0.1"
```

The resolution is documented just below, but a clear message indicating the limitation in TFC would be extremely pragmatic.
```hcl
resource "helm_release" "example" {
  name  = "redis"
  chart = "https://charts.bitnami.com/bitnami/redis-10.7.16.tgz"
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by qwerty1979bg** [comment] 2022-08-10 20:27
@fdr2 The documentation for the "helm_release" resource already [states](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#chart):

> chart - (Required) Chart name to be installed. The chart name can be local path, a URL to a chart, or the name of the chart if repository is specified. It is also possible to use the repository/chart format here if you are running Terraform on a system that the repository has been added to with "helm repo add" but this is not recommended.

Your example fails in the same way, both locally - via Terraform CLI (try in a new VM) and in Terraform Cloud.
It might be succeeding on your computer, because you have already performed the relevant "helm repo add" command.

**Comment by arybolovlev** [comment] 2022-08-25 07:14
Hi @fdr2,

This is expected behavior. In this particular case, version `10.7.16` is not in the Helm chart index and that is the reason you have to provide the full URL to the chart.

Here is how Helm acts and the Helm provider has exactly the same behavior:
```
# helm search repo bitnami/redis --versions

NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/redis        	17.1.2       	7.0.4      	Redis(R) is an open source, advanced key-value ...
...
bitnami/redis        	15.7.0       	6.2.6      	Open source, advanced key-value store. It is of...
```

As you can see, the index has only versions 15.7.0+ and if you try to install one of the old versions, you will get an error message:
```
# helm install redis bitnami/redis --version=10.7.16 

Error: INSTALLATION FAILED: failed to download "bitnami/redis" at version "10.7.16"
```

But you still can install the old version if you want:
```
# helm install redis https://charts.bitnami.com/bitnami/redis-10.7.16.tgz

NAME: redis
LAST DEPLOYED: Thu Aug 25 09:10:29 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

On the opposite, if you try to install a version that is in the index, then no issues:
```
# helm install redis bitnami/redis --version=15.7.0

NAME: redis
LAST DEPLOYED: Thu Aug 25 09:07:30 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: redis
CHART VERSION: 15.7.0
APP VERSION: 6.2.6
```

I will close this issue.

Thank you.

**Closed as completed by arybolovlev** 2022-08-25 07:14 UTC
Labels: enhancement
