### ISSUE TITLE
Migrate repository to a data provider

### ISSUE THREAD

**Issue by meyskens** [hashicorp/terraform-provider-helm#217] opened 2019-02-14 15:41 UTC
There are several open issues about issues with the `helm_repository` resource. After discussion we came to the conclusion to not have this as a resource as there is no remote state.

The `helm_reposoitory` resource should be re-implemented as a data resource with the old `helm_reposoitory` resource being shim to the new data source to not break backwards compatibility.

**Comment by mbarrien** [comment] 2019-02-14 19:25
Related to or duplicate of #146 and #213.

**Closed as completed** 2019-03-07 09:56 UTC

**Comment by pdecat** [comment] 2019-03-07 10:39
I guess I can just close https://github.com/terraform-providers/terraform-provider-helm/pull/187/ following that change.
