### ISSUE TITLE
helm_release resource with array parameters crashes if more than 1 group set

### ISSUE THREAD

**Issue by acesir** [hashicorp/terraform-provider-helm#250] opened 2019-04-12 13:05 UTC
### Terraform Version
Terraform v0.11.13
+ provider.aws v2.5.0
+ provider.helm v0.9.0
+ provider.local v1.2.0
+ provider.null v2.1.0
+ provider.template v2.1.0

### Affected Resource(s)
- helm_resource

### Debug Output
https://gist.github.com/acesir/c4decc3a00f8ef6fcac0992d9a2310b4

### Expected Behavior
helm_release should take the standard input of paramater asdoes helm in format name[0], name[1]

### Actual Behavior
Passing in only one set at position [0] works fine but passing in a second set [1] causes the crash

### Steps to Reproduce
```
resource "helm_release" "jenkins" {
    name      = "jenkins"
    chart     = "${path.module}/helm/jenkins"
    namespace = "build"
    set {
        name = "nfs.server"
        value = "${var.FileSystemID}"
    }
    set {
        name = "Master.HostName"
        value = "jenkins.host"
    }
    set {
        name  = "Agent.volumes[1].type"
        value = "Nfs"
    }
    set {
        name = "Agent.volumes[1].volumeName"
        value = "efs-shared"
    }
    set {
        name = "Agent.volumes[1].serverAddress"
        value = "${var.FileSystemID}"
    }
    set {
        name = "Agent.volumes[1].serverPath"
        value = "/"
    }
    set {
        name = "Agent.volumes[1].mountPath"
        value = "/data/efs-shared"
    }
    set {
        name = "Agent.volumes[0].type"
        value = "HostPath"
    }
    set {
        name = "Agent.volumes[0].volumeName"
        value = "docker-sock-volume"
    }
    set {
        name = "Agent.volumes[0].mountPath"
        value = "/var/run/docker.sock"
    }
    set {
        name = "Agent.volumes[0].hostPath"
        value = "/var/run/docker.sock"
    }
  depends_on = ["null_resource.create-helm"]
}```

**Comment by Swatikp** [comment] 2019-04-25 13:45
I am also facing the same issue. Please help if you found any way.

**Comment by rporres** [comment] 2019-04-29 09:23
@acesir I have working examples with more than 1 group set. I wonder if the problem comes from the fact that not all the keys in group `[1]` are set in group `[0]`

**Comment by guillaumegiordana** [comment] 2019-05-24 12:46
I have the exact problem, is there a possible workaround ? 
@rporres , I experienced the issue when trying to set a value for group [1] without having a group [0].
But also when I have both groups. It's like acesir said, we can't have more than 1 group at a time.

**Comment by guillaumegiordana** [comment] 2019-05-24 15:30
Ok, so I managed to find out what the problem was.
The set method overrides previous declared groups. So if you have group[0] and then group[1], it will only set group[1] in the values. This is why we have a EOF error.

I'm trying to fix it, but i'm not a go programer, so it could take some time.

**Comment by guillaumegiordana** [comment] 2019-05-29 08:27
Ok, so head's up, I found a workaround. Which is not the best solution, but I couldn't find a better solution.
The problem mostly comes from Helm. When you have an array, it doesn't work if the values are not escaped.
For example @acesir, try to put a whitespace at the end of your values, i'm probably sure it'll work.

I went into the provider to try to change the logic of the yaml creation, but the problem is that the yaml doesn't oblige you to have quoted values. So when the go object is converted through the Marshal function, it doesn't put quotes around the values unless you had a special character. I've tried all possible workarounds, but it doesn't work.

So what I did is had a whitespace to the end of my values in my terraform release, and updated my helm chart to trim the whitespaces of theses values. And obviously it worked.

If someone has a better knowledge of golang and can figure out a way to always escape the values, it would be the best solution. In the meantime I will be sticking with my crappy workaround.

@Swatikp @rporres for info :)

**Comment by nitrag** [comment] 2019-07-29 17:44
Same here.  @guillaumegiordana it's not related to different values in different groups. I've got two groups and same (two) values for both.

```
Error: rpc error: code = Unavailable desc = transport is closing

panic: interface conversion: interface {} is nil, not map[string]interface {}

2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: goroutine 87 [running]:
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals.(*parser).listItem(0xc000ac3400, 0xc000ac33a0, 0x2, 0x2, 0x0, 0x1, 0x5b, 0x0, 0x0, 0x0)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals/parser.go:291 +0xf06
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals.(*parser).key(0xc000ac3400, 0xc000abf710, 0xc000aaf270, 0x7)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals/parser.go:177 +0xd0f
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals.(*parser).key(0xc000ac3400, 0xc000abee70, 0x214201d, 0x2621bc0)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals/parser.go:215 +0x1ad
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals.(*parser).parse(0xc000ac3400, 0xc000abee70, 0x0)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals/parser.go:133 +0x38
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals.ParseInto(0xc00016f710, 0x2d, 0xc000abee70, 0x2, 0x2)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/helm/pkg/strvals/parser.go:85 +0xbf
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/helm.getValues(0xc0004c93b0, 0xc000a9e3c0, 0x3f20870, 0xc0005e21a0, 0xc000aaf798, 0x18d0711)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/helm/resource_release.go:583 +0x371
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/helm.resourceReleaseUpdate(0xc0004c93b0, 0x26aa420, 0xc0003365f0, 0x24, 0x3f56fc0)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/helm/resource_release.go:397 +0x58
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00067c480, 0xc0008b9860, 0xc000a90cc0, 0x26aa420, 0xc0003365f0, 0x1, 0xc0005e2178, 0x24ec9e0)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:292 +0x257
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00067c700, 0xc000aafa58, 0xc0008b9860, 0xc000a90cc0, 0xc000887dc8, 0xc0000b8548, 0x24efb00)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ee60, 0x2b1b020, 0xc0006ff0e0, 0xc0000b5b00, 0xc00000ee60, 0xc0006ff0e0, 0xc00072ebd0)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:812 +0x8c7
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x270eec0, 0xc00000ee60, 0x2b1b020, 0xc0006ff0e0, 0xc0008b95e0, 0x0, 0x2b1b020, 0xc0006ff0e0, 0xc000874000, 0x9c4)
2019-07-29T13:32:14.020-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3019 +0x23e
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ee900, 0x2b394a0, 0xc0004cec00, 0xc00062a000, 0xc0007383f0, 0x3f20ce0, 0x0, 0x0, 0x0)
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:966 +0x4b5
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0004ee900, 0x2b394a0, 0xc0004cec00, 0xc00062a000, 0x0)
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0006d4000, 0xc0004ee900, 0x2b394a0, 0xc0004cec00, 0xc00062a000)
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:685 +0x9f
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: created by github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-07-29T13:32:14.021-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:683 +0xa1
2019/07/29 13:32:14 [DEBUG] module.k8s.helm_release.pv-ingress: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalMaybeTainted
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalWriteState
2019/07/29 13:32:14 [TRACE] EvalWriteState: writing current state object for module.k8s.helm_release.pv-ingress
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalApplyProvisioners
2019/07/29 13:32:14 [TRACE] EvalApplyProvisioners: helm_release.pv-ingress is not freshly-created, so no provisioning is required
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalMaybeTainted
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalWriteState
2019/07/29 13:32:14 [TRACE] EvalWriteState: writing current state object for module.k8s.helm_release.pv-ingress
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalIf
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalIf
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalWriteDiff
2019/07/29 13:32:14 [TRACE] module.k8s: eval: *terraform.EvalApplyPost
2019/07/29 13:32:14 [ERROR] module.k8s: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/07/29 13:32:14 [ERROR] module.k8s: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/07/29 13:32:14 [TRACE] [walkApply] Exiting eval tree: module.k8s.helm_release.pv-ingress

```

**Comment by rporres** [comment] 2019-10-21 14:45
Usually these problems are related to how `--set` options are parsed. I'd suggest to run directly `helm` command to see if the problem is reproduced.

Another approach to avoid multiple `set` is to pass directly the yaml you need through the `values` (see and example in https://github.com/terraform-providers/terraform-provider-helm/issues/64#issuecomment-481770248)

**Comment by rporres** [comment] 2019-10-21 14:45
I'm closing this. Feel free to reopen if the problem is not reproduced.

**Closed as completed by rporres** 2019-10-21 14:45 UTC
