### ISSUE TITLE
[PROPOSAL] Switch to Go Modules

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-provider-helm#199] opened 2019-02-04 22:58 UTC
As part of the preparation for Terraform v0.12, we would like to migrate all providers to use [Go Modules](https://github.com/golang/go/wiki/Modules). We plan to continue checking dependencies into vendor/ to remain compatible with existing tooling/CI for a period of time, however go modules will be used for management. Go Modules is the official solution for the go programming language, we understand some providers might not want this change yet, however we encourage providers to begin looking towards the switch as this is how we will be managing all Go projects in the future. Would maintainers please react with :+1: for support, or :-1: if you wish to have this provider omitted from the first wave of pull requests. If your provider is in support, we would ask that you avoid merging any pull requests that mutate the dependencies while the Go Modules PR is open (in fact a total codefreeze would be even more helpful), otherwise we will need to close that PR and re-run `go mod init`. Once merged, dependencies can be added or updated as follows:

```
$ GO111MODULE=on go get github.com/some/module@master
$ GO111MODULE=on go mod tidy
$ GO111MODULE=on go mod vendor
```

GO111MODULE=on might be unnecessary depending on your environment, this example will fetch a module @ master and record it in your project's go.mod and go.sum files. It's a good idea to tidy up afterward and then copy the dependencies into vendor/. To remove dependencies from your project, simply remove all usage from your codebase and run:

```
$ GO111MODULE=on go mody tidy
$ GO111MODULE=on go mod vendor
```

Thank you sincerely for all your time, contributions, and cooperation!

**Comment by alexsomesan** [comment] 2019-02-04 23:14
Hi Alex,

Yeah, I'm aware this one needs to switch to go modules as well.
I've had a quick go at it a while back and `go mod init` didn't import the glide dependencies correctly.
I'll have another go at it and take some time to fix the errors.

**Comment by meyskens** [comment] 2019-02-05 14:02
Closing as duplicate of #196

**Closed as completed by meyskens** 2019-02-05 14:02 UTC
