### ISSUE TITLE
Allow marking values field as sensitive

### ISSUE THREAD

**Issue by subesokun** [hashicorp/terraform-provider-helm#84] opened 2018-06-25 06:58 UTC
Hi, I'm currently in the situation where I've to pass in some credentials via the values but as my Terraform runs as part of a CI/CD pipeline these credentials are visible to everybody with access to the CI/CD logs (which is everybody in our team). Is it possible to mark the values field per default as sensitive or is there any other way to force TF to hide the values output? 

```
helm_release.somechart: Creating...
  <snip>
  values.#:             "" => "1"
  values.0:             "" => "some secret stuff goes here"
```

### Terraform Version
Terraform v0.11.7
Client: v2.9.1+g20adb27
Server: v2.9.0+gf6025bb

### Affected Resource(s)
- helm_repository

**Comment by rawkode** [comment] 2018-07-03 09:15
Potentially a duplicate of #80

**Closed as completed** 2018-11-09 16:43 UTC
Labels: duplicate
