### ISSUE TITLE
Helm provider is not integrating with Kuberenetes cluster

### ISSUE THREAD

**Issue by Ved96** [hashicorp/terraform-provider-helm#1219] opened 2023-08-10 07:36 UTC
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.4.2
Helm Provider version: latest 
Kubernetes version: 2.10
```

### Affected Resource(s)

- helm_provider

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

########### data blocks to call the existing cluster ############
data "aws_eks_cluster" "eks_cluster" {
  name ="eks-cluster"
}

data "terraform_remote_state" "eks" {
  backend = "local"
  config = {
    path = "../../../Resource usage/Networking & Content Delivery/helm/With worker nodes/EKS/terraform.tfstate"
  }
}

data "aws_eks_cluster" "cluster" {
  name = data.terraform_remote_state.eks.outputs.cluster_name
}

data "aws_eks_cluster_auth" "cluster" {
  name = data.terraform_remote_state.eks.outputs.cluster_name
}

####################  module file 
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.eks_cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks_cluster.certificate_authority.0.data)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      args        = ["eks", "get-token", "--cluster-name", data.aws_eks_cluster.eks_cluster.name]
      command     = "aws"
    }
  }
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
}

 resource "helm_release" "example" {
    name  = var.release_name
    chart = var.chart_name
}


you can take a look at the code here
Module folder:-
[Helm.zip](https://github.com/hashicorp/terraform-provider-helm/files/12310010/Helm.zip)
Resource usage folder- 
[Helm-resource usage.zip](https://github.com/hashicorp/terraform-provider-helm/files/12310022/Helm-resource.usage.zip)

```

### Debug Output

[helm-debug.txt](https://github.com/hashicorp/terraform-provider-helm/files/12310046/helm-debug.txt)

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

A ngnix chart should have been installed on the EKS

### Actual Behavior

it threw an error saying provide Kubernetes credentials

### Important Factoids
 NO

### References

- GH-1234
- https://github.com/hashicorp/terraform-provider-aws/issues/32893

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment] 2023-08-10 09:40
The errors in you log are quite explicit about what the issue is. There are two of them actually:

```
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the    
│ root module and configure the provider's required arguments as described in the provider documentation.        
│
╵
╷
│ Error: configuring Terraform AWS Provider: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 7aaa65c2-7498-4e45-9eae-dbbed75d3729, api error InvalidClientTokenId: The security token included in the request is invalid.
```
This refers to the AWS provider not finding valid credentials. Since you're aws provider block only specifies a profile, please check that it's the correct profile and that the profile contains valid credentials in you local aws client configuration.

```
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│
╵
╷
│ Error: Unable to find remote state
│
│   with data.terraform_remote_state.eks,
│   on datasources.tf line 5, in data "terraform_remote_state" "eks":
│    5: data "terraform_remote_state" "eks" {
│
│ No stored state was found for the given workspace in the given backend.
╵
```
This means that the filesystem path that the local state storage is pointing to is not a valid state file path. I'm not 100% sure that relative paths are allowed here, so please try setting an absolute path and make sure it's properly escaped if it's a windows path.

**Comment by alexsomesan** [comment] 2023-08-10 09:43
I will close this because the report doesn't mention any issue specific to the Helm provider, but rather a usage question related to the remote state resource and AWS provider. 

Please re-open if you run into any issues specifically with the Helm provider.

**Closed as completed by alexsomesan** 2023-08-10 09:43 UTC
Labels: question

**Comment by Ved96** [comment] 2023-08-16 05:13
> The errors in you log are quite explicit about what the issue is. There are two of them actually:
> 
> ```
> ╷
> │ Error: Invalid provider configuration
> │
> │ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the    
> │ root module and configure the provider's required arguments as described in the provider documentation.        
> │
> ╵
> ╷
> │ Error: configuring Terraform AWS Provider: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 7aaa65c2-7498-4e45-9eae-dbbed75d3729, api error InvalidClientTokenId: The security token included in the request is invalid.
> ```
> 
> This refers to the AWS provider not finding valid credentials. Since you're aws provider block only specifies a profile, please check that it's the correct profile and that the profile contains valid credentials in you local aws client configuration.
> 
> ```
> │
> │   with provider["registry.terraform.io/hashicorp/aws"],
> │   on <empty> line 0:
> │   (source code not available)
> │
> ╵
> ╷
> │ Error: Unable to find remote state
> │
> │   with data.terraform_remote_state.eks,
> │   on datasources.tf line 5, in data "terraform_remote_state" "eks":
> │    5: data "terraform_remote_state" "eks" {
> │
> │ No stored state was found for the given workspace in the given backend.
> ╵
> ```
> 
> This means that the filesystem path that the local state storage is pointing to is not a valid state file path. I'm not 100% sure that relative paths are allowed here, so please try setting an absolute path and make sure it's properly escaped if it's a windows path.


Hey, I have a valid profile set and I have cross-checked it twice. I can install all charts manually and work using aws CLI. 
could you please give me an example of how can i create a module with helm release and then call the module in the project folder? where should I put the provider.tf file? in the module folder or project folder?
