### ISSUE TITLE
terraform plan is always changing

### ISSUE THREAD

**Issue by venky999** [hashicorp/terraform-provider-helm#436] opened 2020-03-06 14:54 UTC
### Terraform Version
0.12.20

### Affected Resource(s)

- helm : 3.0.0
- helm_provider_release 1.0.0
- helm_repository https://kubernetes-charts.storage.googleapis.com

TF: 

```
resource "helm_release" "nginx-ingress" {
  name  = "nginx-ingress"
  chart = "stable/nginx-ingress"
  version = "1.33.0"
  namespace = "nginx"
  wait = false
  repository = "https://kubernetes-charts.storage.googleapis.com"
}
```

TF: Plan

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 
Terraform will perform the following actions:
 
  # module.helm.helm_release.helm[0] will be created
  + resource "helm_release" "nginx-ingress" {
      + atomic                = false
      + chart                 = "nginx-ingress"
      + cleanup_on_fail       = true
      + dependency_update     = false
      + disable_crd_hooks     = false
      + disable_webhooks      = false
      + force_update          = false
      + id                    = (known after apply)
      + max_history           = 0
      + metadata              = (known after apply)
      + name                  = "nginx-ingress"
      + namespace             = "nginx"
      + recreate_pods         = false
      + render_subchart_notes = true
      + replace               = false
      + repository            = "https://kubernetes-charts.storage.googleapis.com"
      + reset_values          = false
      + reuse_values          = false
      + skip_crds             = false
      + status                = "deployed"
      + verify                = false
      + version               = "1.33.0"
      + wait                  = false
    }
 
```

as shown above terraform plan is always changing after apply

**Comment by venky999** [comment] 2020-03-06 17:19
I found the issue in my case.. The reason is the namespace "nginx" doesn't exist.. so helm_release always showing its creating.. funny thing is since wait is false..we don't see any error and if wait is true.. we just see timeout.. the error message is not clear why it is failed....

**Comment by jrhouston** [comment] 2020-03-06 17:22
Sorry you had this problem @venky999. I see you figured out the root cause here was the namespace error not being captured. The fix for this error being swallowed is in master and will be released soon.

**Comment by venky999** [comment] 2020-03-06 17:30
thank you @jrhouston

**Comment by aareet** [comment] 2020-06-03 22:27
Fix should have been released, closing. Please reopen if this is not the case.

**Closed as completed by aareet** 2020-06-03 22:27 UTC
