### ISSUE TITLE
"wait" argument is not honored

### ISSUE THREAD

**Issue by torumakabe** [hashicorp/terraform-provider-helm#433] opened 2020-03-04 06:38 UTC
### Terraform Version

Terraform v0.12.21
+ provider.azuread v0.7.0
+ provider.azurerm v2.0.0
+ provider.helm v1.0.0
+ provider.kubernetes v1.11.1
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
Excerpt about helm only

```hcl

data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com/"
}

resource "helm_release" "prometheus_operator" {
  name       = "prometheus-operator"
  namespace  = "monitoring"
  repository = data.helm_repository.stable.metadata[0].name
  chart      = "stable/prometheus-operator"
  wait       = false
}
```

### Debug Output

[Debug Output](https://gist.github.com/ToruMakabe/e7e80a25e38bdf19e1df5ca14371df9b)

### Panic Output

N/A

### Expected Behavior

Exit without waiting

### Actual Behavior

Wait and timeout

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

AKS
k8s  Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
k8s Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-13T20:40:52Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jrhouston** [comment] 2020-08-05 16:10
Thanks for opening this @ToruMakabe - I wasn't able to reproduce this with the chart and config in your issue. Can you share the version of your Kubernetes cluster and which provider you are using?

**Comment by torumakabe** [comment] 2020-08-06 00:38
@jrhouston Thanks. As I mentioned , provider.helm v1.0.0 and k8s Server Version v1.16.4. Actually, I replaced terraform to flux/helm-operator for long-running helm deployment. So please close if no one cares this issue.

**Comment by alexsomesan** [comment] 2020-08-12 16:40
Unable to reproduce. Closing for now. Feel free to reopen if additional data becomes available.

**Closed as completed by alexsomesan** 2020-08-12 16:40 UTC
Labels: bug, acknowledged, theme/lifecycle
