### ISSUE TITLE
random EOFs when running agains multiple clusters

### ISSUE THREAD

**Issue by caarlos0** [hashicorp/terraform-provider-helm#347] opened 2019-09-26 13:49 UTC
I have a module that receives the kubeconfig cluster as a variable.
The module then sets up the helm module and installs/upgrade a helm release.

If I declare that module several times on the same terraform file, each instance pointing to different clusters, I eventually get `EOF` errors.

Running with `-parallelism=1` fixes the issue, but take waaaay more time.

Has anyone else experienced this?

_Originally posted by @caarlos0 in https://github.com/terraform-providers/terraform-provider-helm/issues/25#issuecomment-519682989_

**Comment by jacobfoard** [comment] 2019-09-26 15:33
I ran into a similar issue when running our terraform plan/applies via docker (and technically atlantis, but I was able to reproduce just running terraform commands). 
On my local box I didn't have any issues. But adding `-parallelism=1` fixed it for our docker setup.

**Comment by aaronmell** [comment] 2019-10-15 20:42
Do you load the same chart for each cluster? There is a concurrency bug in the chart load function in helm. I modified the provider with a retry and that eliminated most of our failures

**Comment by caarlos0** [comment] 2019-10-15 21:19
yes, most of them are the same charts...

is it on master yet? if so I can help testing :)

**Comment by aaronmell** [comment] 2019-10-16 03:26
No, it was kinda hacky, the bug is still open on helm. I can push my branch
to git if you want to use it though

**Comment by caarlos0** [comment] 2019-10-16 13:00
No need to, I'll wait :)

**Comment by shaneramey** [comment] 2019-10-17 20:29
@aaronmell I'd be interested in seeing your fix, if you would please push it up. I'm seeing a similar issue on EKS (1 cluster only) with TLS enabled (but not with TLS disabled).

**Comment by aaronmell** [comment] 2019-10-17 21:05
https://github.com/aaronmell/terraform-provider-helm/tree/EOF_Retries

**Comment by shaneramey** [comment] 2019-10-20 08:02
Thanks @aaronmell I used the insight from your fork to help create PR https://github.com/terraform-providers/terraform-provider-helm/pull/359. I wonder if that PR will help with this issue.

**Comment by NickCarton** [comment] 2019-11-15 03:07
This absolute ***hemorrhoid*** of an issue has been with me for almost a week, preventing me from releasing production code and finally, I got very upset and ran `helm remove --force`, upgraded to helm 2.16.1 and then ran `helm init --upgrade --service-account tiller` to reinstall the tiller pod.

After all this, I reran my terraform and all is well in the world.

I hope this helps someone.

**Comment by polina-mar** [comment] 2019-11-17 23:32
@NickCarton tried that. Still happening :(

**Comment by caarlos0** [comment] 2019-11-18 00:23
@NickCarton @polina-mar for me running with `-parallelism=1` prevents the issue.

**Comment by polina-mar** [comment] 2019-11-18 03:40
@caarlos0 thanks for your suggestion. Could you please explain how to setup this parameter in Terraform?

**Comment by caarlos0** [comment] 2019-11-18 12:05
@polina-mar just run`terraform apply -parallelism=1`

**Comment by polina-mar** [comment] 2019-11-20 01:41
@caarlos0 unfortunately didn't work :( I set TF_CLI_ARGS_apply and TF_CLI_ARGS_plan to -parallelism=1 in terraform cloud which should be equivalent to CLI arguments https://www.terraform.io/docs/commands/environment-variables.html#tf_cli_args-and-tf_cli_args_name
Still getting same EOFs

**Comment by caarlos0** [comment] 2019-11-20 02:54
I'm running locally... so no idea about this, sorry :(

**Comment by polina-mar** [comment] 2019-11-20 04:13
Seems that setting `TFE_PARALLELISM` to 1 in Terraform Cloud worked. Anyway keeping fingers crossed

**Comment by caarlos0** [comment] 2019-12-02 19:14
did it work @polina-mar ?

**Comment by mcuadros** [comment] 2020-04-10 18:41
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.

**Closed as completed by mcuadros** 2020-04-10 18:41 UTC
