### ISSUE TITLE
terraform refresh is removing namespaces from the cluster / terraform plan is not updating values

### ISSUE THREAD

**Issue by jp** [hashicorp/terraform-provider-helm#36] opened 2018-01-11 22:18 UTC
Hello,

I'm using terraform v0.11.2 with helm provider 0.3.2.

I have 4 namespaces in my cluster, all created with the helm provider.

```
$ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE  
dev-01          1               Thu Jan 11 08:42:29 2018        DEPLOYED           assembly-dev-1.3.0   dev-01     
kube-system     1               Thu Jan 11 08:41:34 2018        DEPLOYED        system-0.13.0           kube-system
lt-01           1               Thu Jan 11 09:14:27 2018        DEPLOYED           assembly-dev-1.4.0   lt-01      
telemetry       1               Thu Jan 11 08:42:29 2018        DEPLOYED        telemetry-1.14.0        telemetry  
dev-02          1               Thu Jan 11 09:14:27 2018        DEPLOYED           assembly-dev-1.4.0   dev-02     

```

I can find those 4 namespaces in the tfstate as expected.

When I'm running terraform refresh, the first time it is manipulating all the namespaces:

```
$ terraform refresh -var-file=../terraform.tfvars -var-file=clusters/dev/cluster.tfvars 2>&1 | more
Acquiring state lock. This may take a few moments...
google_compute_subnetwork.default: Refreshing state... (ID: us-east1/us-east1-pc-dev)
data.google_client_config.current: Refreshing state...
data.template_file.gcloud_credentials: Refreshing state...
google_container_cluster.k8s: Refreshing state... (ID: dev)
null_resource.delete-default-node-pool: Refreshing state... (ID: 3019439159205543985)
google_container_node_pool.k8s: Refreshing state... (ID: us-east1-b/dev/default)
helm_repository.k8s: Refreshing state... (ID: k8s)
helm_chart.kube-system: Refreshing state... (ID: kube-system)
kubernetes_service_account.tiller: Refreshing state... (ID: kube-system/tiller)
null_resource.label-cluster-instances: Refreshing state... (ID: 274257626344228804)
null_resource.helm: Refreshing state... (ID: 1209291922586130472)
helm_chart.k8s[3]: Refreshing state... (ID: dev-01)
helm_chart.k8s[1]: Refreshing state... (ID: telemetry)
helm_chart.k8s[2]: Refreshing state... (ID: dev-02)
helm_chart.k8s[0]: Refreshing state... (ID: lt-01)
Releasing state lock. This may take a few moments...
```

But at that point, some namespaces are deleted from the tfstate.

The following terraform refresh is not manipulating all the namespaces anymore.

```
$ terraform refresh 
data.google_client_config.current: Refreshing state...
google_compute_subnetwork.default: Refreshing state... (ID: us-east1/us-east1-pc-dev)
data.template_file.gcloud_credentials: Refreshing state...
google_container_cluster.k8s: Refreshing state... (ID: dev)
google_container_node_pool.k8s: Refreshing state... (ID: us-east1-b/dev/default)
helm_repository.k8s: Refreshing state... (ID: fleet)
helm_chart.kube-system: Refreshing state... (ID: kube-system)
null_resource.label-cluster-instances: Refreshing state... (ID: 274257626344228804)
kubernetes_service_account.tiller: Refreshing state... (ID: kube-system/tiller)
helm_chart.k8s[2]: Refreshing state... (ID: dev-02)
null_resource.helm: Refreshing state... (ID: 1209291922586130472)
```

At the same time, values and versions are not forced to the cluster. I found the refresh issue while debugging this second issue, I think they are related somehow.

I see on the Readme that the suggestion version for TF is 0.10.\*. Is that a compatibility issue with TF? I can't move back to 0.11.\* as we use some features of this version (GCP backend).

**Comment by rodcloutier** [comment] 2018-01-22 21:45
Latest version is now compiled against 0.11.2. We will try on our side with a recompile.
I am currently trying to reproduce the bug.

**Comment by mcuadros** [comment] 2018-02-26 09:10
@rodcloutier @jp  its happening in the latest versions?

**Comment by rodcloutier** [comment] 2018-02-26 19:34
So far I haven't seen the problem. I couldn't reproduce the bug.

**Comment by mcuadros** [comment] 2020-04-10 17:41
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.

**Closed as completed** 2020-04-10 17:55 UTC
